name = "fluentxverse-site"
account_id = "8355506b306aa26ed64113cdc82cf338"
workers_dev = true
compatibility_date = "2026-10-09"
routes = [
  { pattern = "fluentxverse.com", custom_domain = true },
  { pattern = "www.fluentxverse.com", custom_domain = true }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
