const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const base = process.env.ADMIN_TEST_URL || 'http://localhost:5185';
const now = Date.now(), startsAt = new Date(now + 3600000).toISOString();
const lesson = { bookingId: 'ops-lesson', slotId: 'slot', tutorId: 'tutor', studentId: 'student', slotDateTime: startsAt, durationMinutes: 25, status: 'confirmed', outcome: 'upcoming', tutor: { id: 'tutor', name: 'Test Tutor' }, student: { id: 'student', name: 'Test Student' }, notes: { notesStatus: 'draft', endsAt: new Date(now + 5100000).toISOString() }, presence: [{ role: 'student', callState: 'unknown' }], alert: 'Starting soon' };
const report = { id: 'case', bookingId: 'ops-lesson', source: 'student', reason: 'tutor', tutorIssueLabel: 'Tutor arrived late', details: 'Late entry', priority: 'high', status: 'submitted', resolution: '', dueAt: new Date(now - 1000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), internalHistory: [{ comment: 'Internal case update', actorId: 'admin', at: startsAt }], reviewHistory: [] };
const metric = { slots: { bookable: 5, booked: 2 }, lessons: { attended: 1, teachingHours: 0.42 }, attendance: { present: 1, absent: 0, unverified: 1 }, notes: { overdue: 1 }, reliability: { score: 80 }, cancellation: { rate: 20 }, recentLessons: [lesson] };
const detail = { booking: lesson, tutor: lesson.tutor, student: lesson.student, outcome: 'upcoming', notesState: { endsAt: lesson.notes.endsAt, notesStatus: 'draft', editableUntil: startsAt }, materialRequest: { title: 'Simple Hellos', courseId: 'conversational-skills', level: 1, chapter: 1 }, presence: [], activity: [], recordings: [], materials: [{ materialTitle: 'Simple Hellos', completionStatus: 'in_progress', stoppedAtLabel: 'Practice' }], summary: { studentComment: 'Lesson feedback' }, versions: [{ submittedAt: startsAt, actorId: 'tutor', snapshotJson: '{"summary":{"studentComment":"Saved version"}}' }], reports: [report], transactions: [{ id: 'refund-1', type: 'refund', status: 'completed', createdAt: startsAt }], survey: { rating: 5, comment: 'Private QA comment' }, attendanceHistory: [{ id: 'archive', canRestore: true, reason: 'Attendance changed', createdAt: startsAt }], audits: [{ action: 'notes_reopened', reason: 'Support checked evidence', createdAt: startsAt }] };
detail.penalties = [];
(async () => {
  const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
  await fs.mkdir('../output/screenshots', { recursive: true });
  try {
    for (const width of [1566, 375]) {
      const context = await browser.newContext({ viewport: { width, height: 900 } });
      const writes = [], errors = []; let caps = ['support', 'qa', 'operations', 'finance'], failSave = false;
      await context.route(/\/(admin|tickets)\//, async route => {
        const req = route.request(), url = new URL(req.url()), path = url.pathname;
        const result = data => route.fulfill({ json: { success: true, data } });
        if (path === '/admin/me') return route.fulfill({ json: { success: true, user: { userId: 'admin', username: 'Admin', role: 'superadmin' } } });
        if (path === '/admin/tutors') return result({ tutors: [{ id: 'tutor', givenName: 'Test', familyName: 'Tutor', email: 't@example.test' }], total: 1 });
        if (!path.startsWith('/admin/operations')) return result([]);
        const p = path.replace('/admin/operations', '');
        if (req.method() !== 'GET') { writes.push({ path: p, body: req.postDataJSON() }); return failSave ? route.fulfill({ status: 400, json: { success: false, error: 'Slot no longer available' } }) : result(null); }
        if (p === '/access') return result({ id: 'admin', role: 'superadmin', permissions: caps });
        if (p === '/lessons') return result({ rows: [lesson], total: 1, totalPages: 1 });
        if (p === '/lessons/ops-lesson') return result(detail);
        if (p === '/slots') return result([{ slotId: 'new-slot', startsAt, slotDate: startsAt.slice(0,10), slotTime: '6:00 PM', status: 'open', tutor: lesson.tutor }]);
        if (p === '/reports') return result([report]);
        if (p === '/admins') return result([{ id: 'admin2', name: 'Support Admin', role: 'admin', permissions: ['support'] }]);
        if (p === '/audit') return result(detail.audits);
        if (p === '/surveys') return result({ total: 1, average: 5, responseRate: 50, topics: [{ label: 'Audio quality', positiveEnabled: true, positive: 1, improvement: 0 }], rows: [{ ...detail.survey, bookingId: lesson.bookingId, tutor: lesson.tutor, startsAt }] });
        if (p === '/payments') return result({ rows: detail.transactions, review: [{ bookingId: 'ops-lesson', refundStatus: 'review', refundError: 'Uncertain transfer' }] });
        if (p === '/performance/tutor') return result(metric);
        if (p === '/people/tutor/tutor') return result({ role: 'tutor', person: { ...lesson.tutor, email: 't@example.test', isBlocked: true }, lessons: [lesson], penalties: [{ penaltyId: 'penalty', penaltyCode: '301' }], reports: [report], progress: [], transactions: detail.transactions, performance: metric });
        if (p === '/penalties/penalty/preview') return result({ current: 80, proposed: 100, cancellationBefore: 20, cancellationAfter: 0 });
        return result([]);
      });
      const page = await context.newPage(); page.on('pageerror', e => errors.push(e.message));
      await page.goto(`${base}/lesson-operations`, { waitUntil: 'domcontentloaded' });
      await page.getByText('Starting soon', { exact: true }).waitFor();
      assert((await page.locator('.operations-presence').innerText()).includes('Call unconfirmed'));
      const tab = name => page.getByRole('navigation', { name: 'Operations views' }).getByRole('button', { name, exact: true });
      await page.screenshot({ path: `../output/screenshots/admin-ops-live-${width}.png`, fullPage: true });
      await tab('Lessons').click(); await page.locator('.operations-table-wrap tbody tr').waitFor();
      assert.equal(await page.getByRole('link', { name: 'Open lesson' }).getAttribute('href'), '/lesson-operations/ops-lesson');
      await tab('Schedule').click(); await page.getByRole('heading', { name: 'Published slots' }).waitFor();
      await tab('Notes').click(); await page.locator('.operations-table-wrap tbody tr').waitFor();
      await tab('Issues').click(); await page.getByText('Review overdue', { exact: true }).waitFor();
      await page.getByRole('button', { name: 'Assign & update', exact: true }).click();
      const dialog = page.locator('dialog[open]'); await dialog.waitFor();
      await dialog.getByLabel('Assigned admin').selectOption('admin2');
      await dialog.getByLabel('Priority').selectOption('urgent');
      await dialog.getByLabel('Internal update').fill('Private follow-up');
      await dialog.getByRole('button', { name: 'Confirm', exact: true }).click(); await page.waitForFunction(() => !document.querySelector('dialog[open]'));
      assert.equal(writes.at(-1).body.priority, 'urgent');
      await page.getByRole('button', { name: 'Review', exact: true }).click(); await dialog.waitFor();
      assert.equal(await dialog.getByLabel('Completed refund').locator('option').count(), 2);
      await dialog.getByRole('button', { name: 'Close', exact: true }).click();
      await tab('Feedback').click(); await page.getByText('Private QA comment', { exact: true }).waitFor();
      await page.screenshot({ path: `../output/screenshots/admin-ops-feedback-${width}.png`, fullPage: true });
      await tab('Performance').click(); await page.getByLabel('Tutor', { exact: true }).selectOption('tutor'); await page.getByText('Bookable slots', { exact: true }).waitFor();
      await tab('Payments').click(); await page.getByText('Uncertain transfer', { exact: true }).waitFor(); assert.equal(await page.getByRole('button', { name: 'Approve refund' }).count(), 0);
      await tab('Audit').click(); await page.getByText('Support checked evidence', { exact: true }).waitFor();
      await tab('Permissions').click(); await page.getByRole('button', { name: 'Edit permissions' }).click(); await dialog.waitFor();
      await dialog.getByLabel('qa', { exact: true }).check(); await dialog.getByLabel('Reason', { exact: true }).fill('QA reassignment');
      await dialog.getByRole('button', { name: 'Confirm', exact: true }).click(); await page.waitForFunction(() => !document.querySelector('dialog[open]'));
      assert(writes.at(-1).body.permissions.includes('qa'));
      await page.goto(`${base}/lesson-operations/ops-lesson`, { waitUntil: 'domcontentloaded' });
      await page.getByRole('button', { name: 'Reschedule', exact: true }).waitFor({ timeout: 5000 }).catch(async e => { console.error({ errors, body: await page.locator('body').innerText() }); throw e; });
      await page.getByRole('button', { name: 'Reschedule', exact: true }).click(); await dialog.waitFor();
      await dialog.getByLabel('Available slot').selectOption('new-slot'); await dialog.getByLabel('Reason', { exact: true }).fill('New schedule');
      const box = await dialog.boundingBox(); assert(box.x >= 8 && box.x + box.width <= width - 8); assert(Math.abs(box.x + box.width / 2 - width / 2) < 2);
      failSave = true; await dialog.getByRole('button', { name: 'Confirm', exact: true }).click(); await dialog.getByText('Slot no longer available', { exact: true }).waitFor();
      assert.equal(await dialog.getByLabel('Reason', { exact: true }).inputValue(), 'New schedule');
      await page.screenshot({ path: `../output/screenshots/admin-ops-modal-${width}.png` });
      failSave = false; await dialog.getByRole('button', { name: 'Confirm', exact: true }).click(); await page.waitForFunction(() => !document.querySelector('dialog[open]'));
      assert.equal(writes.at(-1).body.targetSlotId, 'new-slot');
      await page.getByRole('navigation', { name: 'Lesson detail views' }).getByRole('button', { name: 'notes', exact: true }).click();
      await page.getByText('Saved version', { exact: true }).count(); await page.screenshot({ path: `../output/screenshots/admin-ops-notes-${width}.png`, fullPage: true });
      await page.goto(`${base}/operations/people/tutor/tutor`, { waitUntil: 'domcontentloaded' });
      await page.getByRole('button', { name: 'Remove booking restriction' }).waitFor(); await page.getByRole('button', { name: 'penalties', exact: true }).click();
      await page.getByRole('button', { name: 'Revoke penalty' }).click(); await dialog.getByText(/Reliability: 80% to 100%/).waitFor();
      await dialog.getByRole('button', { name: 'Close', exact: true }).click();
      caps = ['support']; await page.goto(`${base}/lesson-operations`, { waitUntil: 'domcontentloaded' }); await page.getByText('Starting soon', { exact: true }).waitFor();
      assert.equal(await tab('Feedback').count(), 0); assert.equal(await tab('Payments').count(), 0);
      assert.deepEqual(errors, []); assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
      console.log(`PASS admin operations ${width}: navigation, cases, privacy, permissions, conflicts, refunds, linked detail and centered dialogs`);
      await context.close();
    }
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
