/**
 * DailyDispatchEditorPage
 * Read-only viewer for Daily Dispatch articles (generated by external microservice)
 */
import { useState, useEffect, useMemo } from 'preact/hooks';
import {
  listDispatchArticles,
  getDispatchArticle,
} from '../api/dailyDispatch.api';
import type {
  StoredLesson,
  DispatchArticleListItem,
} from '../types/dailyDispatch.types';
import { DISPATCH_CATEGORIES } from '../types/dailyDispatch.types';
import { toast } from '../Components/Toast/Toast';
import './DailyDispatchEditorPage.css';

// ============================================================================
// MAIN COMPONENT
// ============================================================================

export default function DailyDispatchEditorPage() {
  const [view, setView] = useState<'list' | 'detail'>('list');
  const [articles, setArticles] = useState<DispatchArticleListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedArticle, setSelectedArticle] = useState<StoredLesson | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterCategory, setFilterCategory] = useState<string>('');

  // Load articles on mount
  useEffect(() => {
    loadArticles();
  }, []);

  const loadArticles = async () => {
    try {
      setLoading(true);
      const data = await listDispatchArticles();
      setArticles(data);
    } catch (error) {
      console.error('Failed to load articles:', error);
      toast.error('Failed to load articles');
    } finally {
      setLoading(false);
    }
  };

  // Filter articles
  const filteredArticles = useMemo(() => {
    return articles.filter(article => {
      const matchesSearch = !searchTerm || 
        article.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        article.topic.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesCategory = !filterCategory || article.category === filterCategory;
      return matchesSearch && matchesCategory;
    });
  }, [articles, searchTerm, filterCategory]);

  // Handle viewing article details
  const handleViewArticle = async (id: string) => {
    try {
      setLoading(true);
      const article = await getDispatchArticle(id);
      setSelectedArticle(article);
      setView('detail');
    } catch (error) {
      console.error('Failed to load article:', error);
      toast.error('Failed to load article');
    } finally {
      setLoading(false);
    }
  };

  // Handle preview in new tab
  const handlePreview = (id: string) => {
    window.open(`/daily-dispatch-preview/${id}`, '_blank');
  };

  // ============================================================================
  // RENDER LIST VIEW
  // ============================================================================
  if (view === 'list') {
    return (
      <div className="dd-page">
        {/* Page Header */}
        <div className="dd-page-header">
          <div className="dd-header-content">
            <div className="dd-header-icon">
              <i className="ri-newspaper-line" />
            </div>
            <div>
              <h1>Daily Dispatch</h1>
              <p>News articles generated by AI microservice</p>
            </div>
          </div>
          <div className="dd-header-stats">
            <div className="dd-stat">
              <span className="dd-stat-value">{articles.length}</span>
              <span className="dd-stat-label">Total Articles</span>
            </div>
          </div>
        </div>

        {/* Filters */}
        <div className="dd-filters">
          <div className="dd-search">
            <i className="ri-search-line" />
            <input
              type="text"
              placeholder="Search articles..."
              value={searchTerm}
              onInput={(e) => setSearchTerm((e.target as HTMLInputElement).value)}
            />
          </div>
          <select
            className="dd-filter-select"
            value={filterCategory}
            onChange={(e) => setFilterCategory((e.target as HTMLSelectElement).value)}
          >
            <option value="">All Categories</option>
            {DISPATCH_CATEGORIES.map(cat => (
              <option key={cat} value={cat}>{cat}</option>
            ))}
          </select>
          <button className="dd-btn dd-btn-ghost" onClick={loadArticles}>
            <i className="ri-refresh-line" />
            Refresh
          </button>
        </div>

        {/* Article List */}
        {loading ? (
          <div className="dd-loading">
            <div className="dd-loading-spinner" />
            <p>Loading articles...</p>
          </div>
        ) : filteredArticles.length === 0 ? (
          <div className="dd-empty">
            <i className="ri-newspaper-line" />
            <h3>No articles found</h3>
            <p>Articles are generated automatically by the AI microservice.</p>
          </div>
        ) : (
          <div className="dd-article-grid">
            {filteredArticles.map(article => (
              <div key={article.id} className="dd-article-card">
                <div className="dd-card-header">
                  <span className="dd-card-category">{article.category}</span>
                  <span className="dd-card-date">{article.postedDate}</span>
                </div>
                <h3 className="dd-card-title">{article.title}</h3>
                <p className="dd-card-topic">{article.topic}</p>
                <div className="dd-card-actions">
                  <button 
                    className="dd-btn dd-btn-sm dd-btn-primary"
                    onClick={() => handleViewArticle(article.id)}
                  >
                    <i className="ri-eye-line" />
                    View Details
                  </button>
                  <button
                    className="dd-btn dd-btn-sm dd-btn-secondary"
                    onClick={() => handlePreview(article.id)}
                  >
                    <i className="ri-external-link-line" />
                    Tutor Preview
                  </button>
                  <button
                    className="dd-btn dd-btn-sm dd-btn-outline"
                    onClick={() => window.open(`/daily-dispatch/student/${article.id}`, '_blank')}
                  >
                    <i className="ri-user-line" />
                    Student Preview
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  // ============================================================================
  // RENDER DETAIL VIEW
  // ============================================================================
  if (!selectedArticle) {
    return (
      <div className="dd-loading">
        <div className="dd-loading-spinner" />
        <p>Loading...</p>
      </div>
    );
  }

  return (
    <div className="dd-detail-page">
      {/* Toolbar */}
      <div className="dd-detail-toolbar">
        <button className="dd-btn-back" onClick={() => setView('list')}>
          <i className="ri-arrow-left-line" />
          Back to List
        </button>
        <div className="dd-detail-title">
          <h2>{selectedArticle.title}</h2>
        </div>
        <button 
          className="dd-btn dd-btn-primary"
          onClick={() => handlePreview(selectedArticle.id)}
        >
          <i className="ri-external-link-line" />
          Preview in New Tab
        </button>
      </div>

      {/* Article Details */}
      <div className="dd-detail-content">
        {/* Metadata Section */}
        <section className="dd-detail-section">
          <div className="dd-section-header">
            <i className="ri-information-line" />
            <h3>Article Metadata</h3>
          </div>
          <div className="dd-metadata-grid">
            <div className="dd-metadata-item">
              <span className="dd-metadata-label">ID</span>
              <span className="dd-metadata-value dd-mono">{selectedArticle.id}</span>
            </div>
            <div className="dd-metadata-item">
              <span className="dd-metadata-label">Title</span>
              <span className="dd-metadata-value">{selectedArticle.title}</span>
            </div>
            <div className="dd-metadata-item">
              <span className="dd-metadata-label">Topic</span>
              <span className="dd-metadata-value">{selectedArticle.topic}</span>
            </div>
            <div className="dd-metadata-item">
              <span className="dd-metadata-label">Category</span>
              <span className="dd-metadata-value dd-badge">{selectedArticle.category}</span>
            </div>
            <div className="dd-metadata-item">
              <span className="dd-metadata-label">Posted Date</span>
              <span className="dd-metadata-value">{selectedArticle.postedDate}</span>
            </div>
            <div className="dd-metadata-item">
              <span className="dd-metadata-label">Created At</span>
              <span className="dd-metadata-value">{new Date(selectedArticle.createdAt).toLocaleString()}</span>
            </div>
          </div>
        </section>

        {/* Warm-up Questions */}
        <section className="dd-detail-section">
          <div className="dd-section-header">
            <i className="ri-chat-smile-line" />
            <h3>Warm-up Questions</h3>
            <span className="dd-count">{selectedArticle.warmUpQuestions.length}</span>
          </div>
          <ul className="dd-question-list">
            {selectedArticle.warmUpQuestions.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </section>

        {/* Vocabulary */}
        <section className="dd-detail-section">
          <div className="dd-section-header">
            <i className="ri-book-open-line" />
            <h3>Vocabulary</h3>
            <span className="dd-count">{selectedArticle.vocabulary.length}</span>
          </div>
          <div className="dd-vocab-grid">
            {selectedArticle.vocabulary.map((vocab, i) => (
              <div key={i} className="dd-vocab-card">
                <div className="dd-vocab-top">
                  <span className="dd-vocab-word">{vocab.word}</span>
                  <span className="dd-vocab-pos">{vocab.partOfSpeech}</span>
                </div>
                <div className="dd-vocab-pronunciation">{vocab.pronunciation}</div>
                <div className="dd-vocab-definition">{vocab.definition}</div>
                <div className="dd-vocab-example">"{vocab.exampleSentence}"</div>
                {vocab.additionalInfo && (
                  <div className="dd-vocab-note">{vocab.additionalInfo}</div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Article Content */}
        <section className="dd-detail-section">
          <div className="dd-section-header">
            <i className="ri-article-line" />
            <h3>Article Content</h3>
            <span className="dd-count">{selectedArticle.articleContent.paragraphs.length} paragraphs</span>
          </div>
          <div className="dd-article-content">
            {selectedArticle.articleContent.paragraphs.map((para, i) => (
              <div key={i} className="dd-paragraph-block">
                <div className="dd-paragraph-number">{i + 1}</div>
                <div className="dd-paragraph-content">
                  <p className="dd-paragraph-text">{para.text}</p>
                  {para.comprehensionQuestion && (
                    <div className="dd-inline-qa">
                      <div className="dd-qa-question">
                        <span className="dd-qa-label">Q:</span>
                        {para.comprehensionQuestion.question}
                      </div>
                      <div className="dd-qa-answer">
                        <span className="dd-qa-label">A:</span>
                        {para.comprehensionQuestion.answer}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
          {selectedArticle.articleContent.source && (
            <div className="dd-source">
              <i className="ri-links-line" />
              {selectedArticle.articleContent.source}
            </div>
          )}
        </section>

        {/* Summary Question */}
        <section className="dd-detail-section">
          <div className="dd-section-header">
            <i className="ri-question-line" />
            <h3>Summary Question</h3>
          </div>
          <div className="dd-summary-box">
            {selectedArticle.summaryQuestion}
          </div>
        </section>

        {/* Discussion Topics */}
        <section className="dd-detail-section">
          <div className="dd-section-header">
            <i className="ri-discuss-line" />
            <h3>Discussion Topics</h3>
          </div>
          <div className="dd-discussions">
            <div className="dd-discussion-block">
              <div className="dd-discussion-header">
                <span className="dd-discussion-badge">A</span>
                <h4>{selectedArticle.discussionA.topic}</h4>
              </div>
              <ul className="dd-discussion-questions">
                {selectedArticle.discussionA.questions.map((q, i) => (
                  <li key={i}>{q}</li>
                ))}
              </ul>
            </div>
            <div className="dd-discussion-block">
              <div className="dd-discussion-header">
                <span className="dd-discussion-badge">B</span>
                <h4>{selectedArticle.discussionB.topic}</h4>
              </div>
              <ul className="dd-discussion-questions">
                {selectedArticle.discussionB.questions.map((q, i) => (
                  <li key={i}>{q}</li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        {/* Raw JSON (for debugging/design) */}
        <section className="dd-detail-section dd-raw-section">
          <div className="dd-section-header">
            <i className="ri-code-line" />
            <h3>Raw Data (JSON)</h3>
            <button 
              className="dd-btn dd-btn-sm dd-btn-ghost"
              onClick={() => {
                navigator.clipboard.writeText(JSON.stringify(selectedArticle, null, 2));
                toast.success('JSON copied to clipboard');
              }}
            >
              <i className="ri-clipboard-line" />
              Copy
            </button>
          </div>
          <pre className="dd-raw-json">
            {JSON.stringify(selectedArticle, null, 2)}
          </pre>
        </section>
      </div>
    </div>
  );
}
