import { useEffect, useState } from 'preact/hooks';
import { useRoute } from 'preact-iso';
import { operations, operationError } from '../api/operations.api';
import { accountLink, dateText, labelText, Fields, History, OperationsAction, IconButton } from '../components/OperationsShared';
import './LessonOperationsPage.css';
function snapshot(json: string) { try { return JSON.parse(json); } catch { return null; } }
export default function OperationsLessonPage() {
  const id = useRoute().params.id;
  const [data, setData] = useState<any>(null), [access, setAccess] = useState<any>(null), [tab, setTab] = useState('overview');
  const [error, setError] = useState(''), [loading, setLoading] = useState(false), [notice, setNotice] = useState(''), [action, setAction] = useState<any>(null);
  const load = async () => { setLoading(true); setError(''); try { setAccess(await operations('/access')); setData(await operations(`/lessons/${encodeURIComponent(id || '')}`)); } catch (e) { setError(operationError(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [id]);
  const can = (cap: string) => access?.permissions.includes(cap), act = (kind: string, extra = {}) => setAction({ kind, id, tutorId: data.tutor.id, ...extra });
  const b = data?.booking, ended = b && Date.now() >= Date.parse(data.notesState.endsAt), future = b && b.status === 'confirmed' && Date.parse(b.slotDateTime) > Date.now();
  return <div className="lesson-operations"><a href="/lesson-operations"><i aria-hidden="true" className="ri-arrow-left-line" /> Lesson Operations</a><header><div><h1>Lesson Detail</h1><span>{id}</span></div><IconButton icon="refresh" title="Refresh" disabled={loading} onClick={load} /></header>
    {error && <p role="alert" className="operations-error">{error}</p>}{notice && <p role="status">{notice}</p>}{loading && <p>Loading...</p>}
    {data && <><div className="operations-metrics"><article><span>Schedule</span><strong className="operations-small-value">{dateText(b.slotDateTime)}</strong></article><article><span>Outcome</span><strong className="operations-small-value">{labelText(data.outcome)}</strong></article><article><span>Tutor</span><a href={accountLink('tutor', data.tutor.id)}>{data.tutor.name}</a></article><article><span>Student</span><a href={accountLink('student', data.student.id)}>{data.student.name}</a></article></div>
    <div className="operations-toolbar">
      {can('support') && <><button onClick={() => act('attendance', { status: 'present' })}><i aria-hidden="true" className="ri-user-follow-line" />Correct to present</button><button onClick={() => act('attendance', { status: 'absent' })}><i aria-hidden="true" className="ri-user-unfollow-line" />Correct to absent</button>{ended && data.notesState.notesStatus !== 'not_required' && <button onClick={() => act('reopen')}><i aria-hidden="true" className="ri-edit-line" />Reopen notes</button>}</>}
      {can('operations') && future && <><button disabled={Date.parse(b.slotDateTime) <= Date.now() + 5 * 60000} onClick={() => act('reschedule')}><i aria-hidden="true" className="ri-calendar-event-line" />Reschedule</button><button onClick={() => act('cancel')}><i aria-hidden="true" className="ri-close-circle-line" />Cancel lesson</button></>}
      {can('finance') && (ended || b.status === 'cancelled') && !b.refunded && <button disabled={b.refundStatus === 'review'} onClick={() => act('refund')}><i aria-hidden="true" className="ri-refund-line" />Approve refund</button>}
    </div>
    <nav className="operations-tabs" aria-label="Lesson detail views">{['overview', 'evidence', 'notes', 'issues', 'feedback', 'tickets', 'history'].filter(key => key !== 'tickets' || can('finance')).map(key => <button className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{labelText(key)}</button>)}</nav>
    {tab === 'overview' && <><section><h2>Attendance & timing</h2><Fields value={{ durationMinutes: b.durationMinutes || 25, status: b.status, tutorAttendance: b.attendanceTutor || 'unverified', studentAttendance: b.attendanceStudent === 'absent' ? 'absent' : 'present', firstRoomEntry: b.tutorRoomEnteredAt, scheduledAttendanceEvidence: b.tutorRoomAttendedAt, editableUntil: data.notesState.editableUntil, notesStatus: data.notesState.notesStatus, refundStatus: b.refundStatus || 'none' }} /></section><section><h2>Material request</h2><Fields value={data.materialRequest} /></section><section><h2>Penalty ledger</h2>{data.penalties.map((p: any) => <article className="operations-record"><Fields value={p} />{can('operations') && !p.revokedAt && p.status !== 'voided' && p.penaltyCode !== '601' && <button onClick={() => act('revoke', { id: p.penaltyId })}><i aria-hidden="true" className="ri-close-circle-line" />Revoke penalty</button>}</article>)}{!data.penalties.length && <p>No penalties.</p>}</section></>}
    {tab === 'evidence' && <><section><h2>Room presence</h2><Fields value={data.presence} /></section><section><h2>Browser-reported call connection</h2><Fields value={data.mediaObservations || []} /></section><section><h2>Classroom activity</h2><Fields value={data.activity} /></section>{can('qa') && <section><h2>Recordings</h2><a href={`/recordings?booking=${encodeURIComponent(id || '')}`}><i aria-hidden="true" className="ri-video-line" />Open recordings</a><Fields value={data.recordings} /></section>}</>}
    {tab === 'notes' && <><section><h2>Lesson summary</h2><Fields value={data.summary} /></section><section><h2>Materials & learning notes</h2><Fields value={data.materials} /></section><section><h2>Submitted versions</h2>{data.versions.map((v: any) => <details className="operations-record"><summary>{dateText(v.submittedAt)} · {v.actorId}</summary><Fields value={snapshot(v.snapshotJson)} /></details>)}{!data.versions.length && (data.published ? <Fields value={snapshot(data.published.snapshotJson)} /> : <p>No submitted versions.</p>)}</section></>}
    {tab === 'issues' && <section><h2>Issue reports</h2>{data.reports.map((r: any) => <article className="operations-record"><strong>{r.tutorIssueLabel || r.studentIssueLabel || r.reason}</strong><p>{r.details}</p><p>{labelText(r.status)} · {labelText(r.priority)} · {dateText(r.createdAt)}</p><p>{r.resolution}</p>{can('support') && <div className="operations-toolbar"><button onClick={() => act('case', { report: r })}>Assign & update</button><button onClick={() => act('review', { report: r })}>Review</button></div>}<History rows={[...(r.internalHistory || []), ...(r.reviewHistory || [])]} /></article>)}{!data.reports.length && <p>No reports.</p>}</section>}
    {tab === 'feedback' && <section><h2>Student feedback</h2><Fields value={data.survey} /></section>}
    {tab === 'tickets' && <section><h2>Ticket transactions</h2><Fields value={data.transactions} /></section>}
    {tab === 'history' && <><h2>Attendance history</h2>{data.attendanceHistory.map((a: any) => <article className="operations-record"><History rows={[a]} />{a.canRestore && can('support') && <button onClick={() => act('restore', { auditId: a.id })}><i aria-hidden="true" className="ri-history-line" />Recover archived notes</button>}</article>)}<h2>Operations history</h2><History rows={data.audits} /></>}
    </>}
    {action && <OperationsAction key={`${action.kind}:${action.id}`} action={action} permissions={access?.permissions} onClose={() => setAction(null)} onSaved={async () => { setNotice('Changes saved.'); await load(); }} />}
  </div>;
}
