import React, { useState } from 'react';
import { FaChevronDown, FaChevronUp } from 'react-icons/fa';
import './FAQ.css';

interface FAQItem {
  question: string;
  answer: string;
}

const FAQ: React.FC = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  const faqs: FAQItem[] = [
    {
      question: "What kind of technology does Decentragri use to collect real-time farming data?",
      answer: "Decentragri deploys a compact multi-sensor field unit equipped with precision-grade probes to measure critical agricultural parameters such as soil pH, moisture levels, ambient sunlight, temperature, and more. These sensors are designed to provide real-time, high-resolution insights tailored for modern farming needs."
    },
    {
      question: "Is Decentragri hardware compatible with all types of farms?",
      answer: "Yes. Our sensor systems are optimized for both smallholder and large-scale farms. Whether you're managing a backyard plot or a commercial plantation, our adaptive hardware can be easily deployed and scaled to your operational needs."
    },
    {
      question: "How is the collected data processed and used?",
      answer: "Data is transmitted to our AI-powered cloud platform where it's analyzed in real time. The system then provides actionable insights and recommendations, helping farmers make smarter decisions on irrigation, fertilization, and planting strategies."
    },
    {
      question: "What makes Decentragri's recommendations trustworthy?",
      answer: "All insights generated by Decentragri are backed by a blockchain-based verification layer. This ensures complete data transparency and immutability, giving you confidence in every recommendation."
    },
    {
      question: "Do I need an internet connection for Decentragri to work?",
      answer: "While our platform performs best with continuous connectivity, we also support offline data caching and delayed transmission to accommodate remote areas with intermittent internet access."
    },
    {
      question: "Can Decentragri help with sustainability efforts?",
      answer: "Absolutely. By optimizing resource use and minimizing environmental impact, Decentragri empowers farmers to adopt sustainable practices without compromising yield or efficiency."
    }
  ];

  const toggleFAQ = (index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <section className="faq-section">
      <div className="container">
        <div className="section-header">
        <h2 className="section-title">
            <span>Frequently Asked</span>
            <span className="text-accent">Questions</span>
          </h2>
          <p>Find answers to common questions about our platform and services</p>
        </div>
        <div className="faq-container">
          {faqs.map((faq, index) => (
            <div 
              key={index} 
              className={`faq-item ${activeIndex === index ? 'active' : ''}`}
              onClick={() => toggleFAQ(index)}
            >
              <div className="faq-question">
                <h3>{faq.question}</h3>
                <span className="faq-toggle">
                  {activeIndex === index ? <FaChevronUp /> : <FaChevronDown />}
                </span>
              </div>
              {activeIndex === index && (
                <div className="faq-answer">
                  <p>{faq.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQ;
